### PR TITLE
Replace `in_group` with `member_of`.

### PR DESCRIPTION
**Pull request by jeffchao**
Replace `in_group` with `member_of`.

### CODE REVIEW

**Comment by jeffchao** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #3** <a href="https://app.graphite.dev/github/pr/abbeylabs/policy-library/3?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #4** <a href="https://app.graphite.dev/github/pr/abbeylabs/policy-library/4?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/abbeylabs/policy-library/4?utm_source=stack-comment).

**Review by songe — COMMENTED** [review]
LGTM overall. Curious, it possible to make one an alias of the other?

**Comment by jeffchao** [comment]
Definitely possible (and easy!). Let's keep a single API for now though.

**Review by hatim-khan — APPROVED** [review]

**Comment by jeffchao** [comment]
### Merge activity

* **Jan 12, 4:56 PM**: @jeffchao started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/abbeylabs/policy-library/4).
* **Jan 12, 4:57 PM**: @jeffchao merged this pull request with [Graphite](https://app.graphite.dev/github/pr/abbeylabs/policy-library/4).

**Pull request merged**
